const $=id=>document.getElementById(id),S=Survey,uid=()=>crypto.randomUUID?crypto.randomUUID():Array.from(crypto.getRandomValues(new Uint8Array(16)),b=>b.toString(16).padStart(2,'0')).join('');
let state={name:'Untitled survey',zone:44,hemisphere:'N',features:[]},selected=null,history=[],redoHistory=[],editSession=null,cacheReady=false,mapPick=null;
try{const saved=localStorage.getItem('line-survey-v1');if(saved)state=S.validate(JSON.parse(saved))}catch(e){setTimeout(()=>toast('Saved project could not be read. Restore a backup.'),500)}
const map=L.map('map',{zoomControl:false,rotate:true,bearing:0,touchRotate:true,rotateControl:false,preferCanvas:true}).setView([17.4,78.5],7),drawing=L.layerGroup().addTo(map),gpsLayer=L.layerGroup().addTo(map);
const osm=L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'});
const satellite=L.tileLayer('https://services.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}',{maxZoom:19,attribution:'Imagery © <a href="https://www.arcgis.com/home/item.html?id=10df2279f9684e4a9f6a7f08febac2a9">Esri</a>, Vantor, Earthstar Geographics, and the GIS User Community'});
const controls=document.createElement('div');controls.className='layer-controls';controls.innerHTML='<div class="section-title">MAP LAYERS</div><label>Background<select id="background"><option value="plain">Plain · offline</option><option value="osm">OpenStreetMap · online</option></select></label><label class="check"><input type="checkbox" id="showactive" checked> Working survey</label><label class="check"><input type="checkbox" id="showfinal" checked> Finalized projects</label><label class="check"><input type="checkbox" id="showvillages" checked> Village names</label><label>Import into<select id="importgroup"><option value="active">Working survey</option><option value="final">Finalized projects · locked</option><option value="village">Village names · points only</option></select></label><button id="village" style="width:100%;margin-top:8px">＋ Village name</button><hr>';
$('features').before(controls);
const satelliteOption=document.createElement('option');satelliteOption.value='satellite';satelliteOption.textContent='Satellite · online';$('background').append(satelliteOption);
const classify=document.createElement('button');classify.id='classify';classify.textContent='Move to layer';$('rename').before(classify);
const exportNote=document.createElement('p');exportNote.className='muted';exportNote.textContent='Exports include visible layers only. KML keeps geometry, names and descriptions; original styling and attachments are not retained.';document.querySelector('.exports').after(exportNote);
document.querySelectorAll('label.file').forEach(label=>{label.tabIndex=0;label.setAttribute('role','button');label.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();label.querySelector('input').click()}})});
const groupLabel={active:'Working survey',final:'Finalized projects',village:'Village names'};
function group(f){return f.group||'active'}function visible(f){return f.projectHidden!==true&&f.folderHidden!==true&&!(f.hiddenFolders||[]).length&&f.hidden!==true&&$('show'+(group(f)==='active'?'active':group(f)==='final'?'final':'villages')).checked}
function toast(s){$('toast').textContent=s;$('toast').style.display='block';clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('toast').style.display='none',6000)}
function commit(fn){const old=JSON.stringify(state);fn();try{S.validate(state)}catch(e){state=JSON.parse(old);toast(e.message);return}if(editSession){render();return}redoHistory=[];history.push(old);if(history.length>30)history.shift();persist();render()}
function persist(){try{localStorage.setItem('line-survey-v1',JSON.stringify(state));$('saved').textContent='Saved on this device · '+new Date().toLocaleTimeString()}catch(e){$('saved').textContent='Device storage full — export a backup now.';toast('Changes are in memory only. Export a backup now.')}}
function active(){return state.features.find(f=>f.id===selected)}
function locked(){return active()&&group(active())==='final'}
function select(id){if(mapPick)return;selected=id;render()}
function render(){ $('project').value=state.name;$('zone').value=state.zone;$('hemisphere').value=state.hemisphere;$('count').textContent=state.features.length;$('undo').disabled=!history.length;$('redo').disabled=!redoHistory.length||!!editSession;$('undo').disabled=!history.length||!!editSession;$('empty').style.display=state.features.length?'none':'block';$('title').textContent=state.name;$('summary').textContent=`${state.features.filter(f=>f.type==='Point'&&group(f)!=='village').length} towers · ${state.features.filter(f=>f.type==='LineString').length} routes · ${state.features.filter(f=>group(f)==='village').length} village points · ${state.features.filter(f=>f.type==='Polygon').length} polygons`;
 if(!document.body.classList.contains('field-layout')){$('features').replaceChildren();for(const g of ['active','final','village']){const fs=state.features.filter(f=>group(f)===g);if(!fs.length)continue;const heading=document.createElement('p');heading.className='muted';heading.textContent=groupLabel[g];$('features').append(heading);for(const f of fs){const b=document.createElement('button');b.className='layer'+(f.id===selected?' active':'');const t=document.createElement('span');t.textContent=f.name;const sub=document.createElement('small');sub.textContent=`${f.type==='Point'?'Point':(f.type==='Polygon'?'Polygon · ':'')+f.points.length+' vertices'}${g==='final'?' · Locked':''}`;b.append(t,sub);b.onclick=()=>select(f.id);const row=document.createElement('div');row.className='feature-visibility';const check=document.createElement('input');check.type='checkbox';check.checked=f.hidden!==true;check.setAttribute('aria-label','Show '+f.name);check.onchange=()=>{f.hidden=!check.checked;persist();render()};row.append(check,b);$('features').append(row)}}}
 renderMap(false);
 const f=active();$('edit-title').textContent=f?f.name:'Vertex editor';$('edit-hint').textContent=f?(locked()?(f.type==='Polygon'?'Polygon boundary: read-only; all rings are retained in exports.':'Finalized project: locked. Move to Working survey to edit.'):'Edit coordinates or drag selected vertices on the map.'):'Select a layer to inspect and edit coordinates.';for(const id of ['rename','append','remove'])$(id).disabled=!f||locked();$('rename').disabled=!f||group(f)==='final';$('remove').disabled=!f||group(f)==='final';$('append').disabled=!f||locked()||f.type!=='LineString';$('classify').disabled=!f;$('vertices').replaceChildren();if(f&&!$('editor').hidden)f.points.forEach((p,i)=>{const tr=document.createElement('tr');[S.vertexLabel(f,i),p.lat.toFixed(7),p.lon.toFixed(7),p.alt===null?'—':p.alt].forEach(v=>{const td=document.createElement('td');td.textContent=v;tr.append(td)});const td=document.createElement('td'),b=document.createElement('button');b.textContent='Edit';b.disabled=locked();b.onclick=()=>editVertex(i);td.append(b);if(f.type==='LineString'){const insert=document.createElement('button');insert.textContent='+ After';insert.setAttribute('aria-label',`Insert vertex after ${i+1}`);insert.disabled=locked();insert.onclick=()=>modal('Insert route vertex',pointFields(),v=>{const p=toPoint(v);commit(()=>f.points.splice(i+1,0,p))});td.append(insert)}if(f.type==='LineString'&&f.points.length>2){const del=document.createElement('button');del.textContent='×';del.setAttribute('aria-label',`Delete vertex ${i+1}`);del.disabled=locked();del.onclick=()=>commit(()=>f.points.splice(i,1));td.append(del)}tr.append(td);$('vertices').append(tr)})}
const pointDrawing=L.layerGroup().addTo(map),pointMarkerCache=new Map();
function renderMap(viewportOnly=false){ const viewportBounds=map.getBounds().pad(.15),visibleMarkers=new Set(),labelCells=new Set();if(!viewportOnly){drawing.clearLayers();pointDrawing.clearLayers();pointMarkerCache.clear()}for(const f of state.features){if(!visible(f))continue;if(f.type==='Polygon'){if(viewportOnly)continue;const shape=L.polygon(S.rings(f).map(r=>r.map(p=>[p.lat,p.lon])),{...FeatureStyle.path(f),weight:FeatureStyle.get(f).width+(f.id===selected?3:0),fillOpacity:f.id===selected?Math.max(.2,FeatureStyle.get(f).fillOpacity):FeatureStyle.get(f).fillOpacity}).addTo(drawing);const label=document.createElement('span');label.textContent=f.name;shape.bindTooltip(label);shape.on('click',()=>{if(!mapPick)select(f.id)});continue}const chosen=f.id===selected,color=group(f)==='final'?'#637e96':group(f)==='village'?'#8c5f9c':f.sourceColor||(chosen?'#167e97':'#d99a31');if(f.type==='LineString'&&!viewportOnly)L.polyline(f.points.map(p=>[p.lat,p.lon]),{...FeatureStyle.path(f),weight:FeatureStyle.get(f).width+(chosen?4:0)}).on('click',e=>{if(mapPick){L.DomEvent.stopPropagation(e.originalEvent);finishPick({lat:e.latlng.lat,lon:((e.latlng.lng+180)%360+360)%360-180})}else select(f.id)}).addTo(drawing);for(let i=0;i<f.points.length;i++){const p=f.points[i];if(!viewportBounds.contains([p.lat,p.lon])||f.type==='LineString')continue;const markerKey=f.id+':'+i;visibleMarkers.add(markerKey);let marker=pointMarkerCache.get(markerKey);if(!marker){marker=L.marker([p.lat,p.lon],{icon:f.type==='Point'?FeatureStyle.icon(f,chosen):L.divIcon({className:'vertex-dot'+(chosen?' selected':''),iconSize:[13,13],iconAnchor:[6,6]}),bubblingMouseEvents:false,draggable:!mapPick&&chosen&&group(f)!=='final'}).addTo(pointDrawing);pointMarkerCache.set(markerKey,marker);const text=document.createElement('span');text.textContent=p.label||(f.type==='Point'?f.name:`V${i+1}`);marker.on('click',e=>{if(window.NVVAcceptPoint?.(p)){if(e.originalEvent)L.DomEvent.stopPropagation(e.originalEvent);return}if(mapPick){L.DomEvent.stopPropagation(e.originalEvent);finishPick(p)}else select(f.id)});marker.on('dragend',()=>{const ll=marker.getLatLng();commit(()=>{p.lat=ll.lat;p.lon=((ll.lng+180)%360+360)%360-180})})}const screen=map.latLngToContainerPoint([p.lat,p.lon]),cell=Math.floor(screen.x/120)+':'+Math.floor(screen.y/40),permanent=chosen||!labelCells.has(cell);labelCells.add(cell);if(marker._nvvLabelPermanent!==permanent){marker.unbindTooltip();marker.bindTooltip(FeatureStyle.label(f,f.name||p.label||'Point'),{permanent,direction:'top',offset:[0,-8],className:'survey-point-label',opacity:1});marker._nvvLabelPermanent=permanent;}}}
for(const [id,marker]of pointMarkerCache)if(!visibleMarkers.has(id)){pointDrawing.removeLayer(marker);pointMarkerCache.delete(id)}
}
function fit(){const ps=state.features.filter(visible).flatMap(f=>f.points.map(p=>[p.lat,p.lon]));if(ps.length)map.fitBounds(L.latLngBounds(ps),{padding:[45,45],maxZoom:17})}
function modal(title,fields,save){if(!title.startsWith('Save '))$('dialog').classList.remove('feature-save-dialog');$('dialog-title').textContent=title;$('fields').replaceChildren();$('form-error').textContent='';for(const f of fields){const label=document.createElement('label');label.textContent=f.label;const input=document.createElement(f.options?'select':'input');input.name=f.id;if(f.options)for(const [v,t]of f.options){const opt=document.createElement('option');opt.value=v;opt.textContent=t;input.append(opt)}else{input.type=f.type||'text';if(f.type==='number')input.step='any'}input.value=f.value??'';input.required=!!f.required;label.append(input);$('fields').append(label)}$('form').onsubmit=e=>{e.preventDefault();try{save(Object.fromEntries(new FormData($('form'))));$('dialog').close()}catch(e){$('form-error').textContent=e.message}};if(fields.some(f=>f.id==='lat')&&fields.some(f=>f.id==='lon'))coordinateSources();$('dialog').showModal()}
$('cancel').onclick=()=>$('dialog').close();
const pickBanner=document.createElement('div');pickBanner.id='pick-banner';pickBanner.hidden=true;pickBanner.innerHTML='<span role="status"></span><button type="button">Cancel pick</button>';$('map').append(pickBanner);L.DomEvent.disableClickPropagation(pickBanner);L.DomEvent.disableScrollPropagation(pickBanner);
function pickingUI(on){for(const selector of ['aside','#editor','.mapbar','header'])document.querySelector(selector).inert=on;$('map').classList.toggle('picking',on);pickBanner.hidden=!on;render();if(on)$('empty').style.display='none'}
function finishPick(point){const request=mapPick;if(!request)return;mapPick=null;pickingUI(false);if(point)request.apply(point);$('dialog').showModal();request.button.focus();}
pickBanner.querySelector('button').onclick=()=>finishPick();
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&mapPick){e.preventDefault();finishPick()}});
map.on('click',e=>{if(mapPick)finishPick({lat:e.latlng.lat,lon:((e.latlng.lng+180)%360+360)%360-180})});
function coordinateSources(latName='lat',lonName='lon',title='Position'){
 const lat=$('form').elements.namedItem(latName),lon=$('form').elements.namedItem(lonName);if(!lat||!lon)return;
 const box=document.createElement('section');box.className='coordinate-source';const label=document.createElement('strong');label.textContent=title;const actions=document.createElement('div');actions.className='row';const pick=document.createElement('button'),known=document.createElement('button');pick.type=known.type='button';pick.textContent='Pick from map';known.textContent='Use known point';pick.setAttribute('aria-label',`${title}: Pick from map`);known.setAttribute('aria-label',`${title}: Use known point`);actions.append(pick,known);const status=document.createElement('p');status.className='muted';status.setAttribute('role','status');status.textContent='Enter coordinates, pick the map, or reuse a loaded point. Name and altitude stay unchanged.';
 const panel=document.createElement('div');panel.hidden=true;const searchLabel=document.createElement('label');searchLabel.textContent='Find a tower or vertex';const search=document.createElement('input');search.type='search';search.placeholder='Search by name';searchLabel.append(search);const list=document.createElement('div');list.className='known-points';panel.append(searchLabel,list);box.append(label,actions,status,panel);lat.closest('label').before(box);
 const apply=p=>{lat.value=String(p.lat);lon.value=String(p.lon);status.textContent=`Coordinates selected: ${p.lat.toFixed(7)}°, ${p.lon.toFixed(7)}°. Click Save to apply.`;panel.hidden=true;};
 pick.onclick=()=>{mapPick={apply,button:pick};$('dialog').close();pickBanner.querySelector('span').textContent=`${title}: tap the map, or tap a loaded point to use its exact coordinates.`;pickingUI(true);$('map').scrollIntoView({block:'center',behavior:'instant'});map.invalidateSize();};
 function results(){list.replaceChildren();const q=search.value.trim().toLowerCase();let count=0;for(const f of state.features)for(let i=0;i<f.points.length;i++){const p=f.points[i],name=`${f.name} · ${p.label|| (f.type==='Point'?'Tower / point':`V${i+1}`)} · ${groupLabel[group(f)]||'Working survey'}`;if(q&&!name.toLowerCase().includes(q))continue;if(++count>100)continue;const button=document.createElement('button');button.type='button';button.textContent=name;button.onclick=()=>apply(p);list.append(button)}if(!count){const empty=document.createElement('p');empty.textContent='No matching points. Import a survey or enter coordinates.';list.append(empty)}else if(count>100){const note=document.createElement('p');note.textContent=`Showing 100 of ${count} matches. Type a name to narrow the list.`;list.append(note)}}
 known.onclick=()=>{panel.hidden=!panel.hidden;if(!panel.hidden){results();search.focus()}};search.oninput=results;
}
function pointFields(p={}){return [{id:'label',label:'Vertex / location name',value:p.label||''},{id:'lat',label:'Latitude (WGS 84 degrees)',type:'number',value:p.lat,required:true},{id:'lon',label:'Longitude (WGS 84 degrees)',type:'number',value:p.lon,required:true},{id:'alt',label:'Source altitude (optional, metres)',type:'number',value:p.alt}]}
function toPoint(v){const p={label:v.label.trim(),lat:Number(v.lat),lon:Number(v.lon),alt:v.alt===''?null:Number(v.alt)};if(!S.valid(p))throw Error('Enter latitude −90 to 90 and longitude −180 to 180.');return p}
function editVertex(i){const f=active();modal('Edit vertex',pointFields(f.points[i]),v=>{const p=toPoint(v);commit(()=>{Object.assign(f.points[i],p);if(f.type==='Polygon'){let offset=0;for(const n of f.ringLengths){if(i===offset)Object.assign(f.points[offset+n-1],p);if(i===offset+n-1)Object.assign(f.points[offset],p);offset+=n}}})})}
function newPoint(g='active'){const c=map.getCenter();modal(g==='village'?'Add village name':'Add tower',pointFields({lat:+c.lat.toFixed(7),lon:+c.lng.toFixed(7)}),v=>{const p=toPoint(v);if(!p.label)throw Error('Enter a location name.');commit(()=>{const f={id:uid(),name:p.label,type:'Point',group:g,points:[p]};state.features.push(f);selected=f.id})})}
$('newpoint').onclick=()=>newPoint();$('village').onclick=()=>newPoint('village');
$('newline').onclick=()=>{modal('New route',[
 {id:'name',label:'Route name',required:true},
 {id:'startLat',label:'Start latitude °',type:'number',required:true},{id:'startLon',label:'Start longitude °',type:'number',required:true},
 {id:'endLat',label:'End latitude °',type:'number',required:true},{id:'endLon',label:'End longitude °',type:'number',required:true}
],v=>{const pts=[{lat:Number(v.startLat),lon:Number(v.startLon),alt:null},{lat:Number(v.endLat),lon:Number(v.endLon),alt:null}];if(!pts.every(S.valid)||!v.name.trim())throw Error('Enter a route name and two valid endpoints.');if(pts[0].lat===pts[1].lat&&pts[0].lon===pts[1].lon)throw Error('Start and end must be different points.');commit(()=>{const f={id:uid(),name:v.name.trim(),type:'LineString',group:'active',points:pts};state.features.push(f);selected=f.id});fit()});coordinateSources('startLat','startLon','Start point');coordinateSources('endLat','endLon','End point');};
$('append').onclick=()=>{const f=active();modal('Append route vertex',pointFields(),v=>{const p=toPoint(v);commit(()=>f.points.push(p))})};$('rename').onclick=()=>{const f=active();modal('Rename layer',[{id:'name',label:'Layer name',value:f.name,required:true}],v=>{if(!v.name.trim())throw Error('Enter a name.');commit(()=>{f.name=v.name.trim();if(f.type==='Point')f.points[0].label=f.name})})};$('remove').onclick=()=>{const f=active();if(!f||locked())return;if(confirm('Delete '+f.name+'?'))commit(()=>{state.features=state.features.filter(x=>x.id!==f.id);selected=null})};$('classify').onclick=()=>{const f=active();modal('Move to map layer',[{id:'group',label:'Destination',value:group(f),options:Object.entries(groupLabel).filter(([g])=>g!=='village'||f.type==='Point')}],v=>commit(()=>f.group=v.group))};
$('undo').onclick=()=>{if(!history.length)return;redoHistory.push(JSON.stringify(state));state=JSON.parse(history.pop());if(!active())selected=null;persist();render()};$('redo').onclick=()=>{if(!redoHistory.length)return;history.push(JSON.stringify(state));state=JSON.parse(redoHistory.pop());if(!active())selected=null;persist();render()};$('fit').onclick=fit;for(const id of ['showactive','showfinal','showvillages'])$(id).onchange=render;
$('project').onchange=e=>commit(()=>state.name=e.target.value.trim()||'Untitled survey');$('zone').onchange=e=>commit(()=>state.zone=Number(e.target.value));$('hemisphere').onchange=e=>commit(()=>state.hemisphere=e.target.value);
$('background').onchange=()=>{map.removeLayer(osm);map.removeLayer(satellite);const choice=$('background').value;if(choice==='osm')osm.addTo(map);if(choice==='satellite')satellite.addTo(map);document.querySelector('.mapfoot span').textContent=choice==='satellite'?'Satellite imagery · online':choice==='osm'?'OpenStreetMap · online background':'Plain map · available offline';if(choice!=='plain')toast('Online background selected. Use Plain when working without internet.');try{localStorage.setItem('line-survey-background',choice)}catch{}};
satellite.on('tileerror',()=>{if(!satellite.warned){toast('Satellite imagery could not load. Check internet or choose another background.');satellite.warned=true}});
osm.on('tileerror',()=>{if(!osm.warned){toast('Background tiles could not load. Use Plain for offline work.');osm.warned=true}});
function parseKML(text,filename,g){const doc=new DOMParser().parseFromString(text,'application/xml');if(doc.getElementsByTagName('parsererror').length||doc.documentElement.localName!=='kml')throw Error('This is not a valid KML document.');const all=(el,n)=>Array.from(el.getElementsByTagNameNS('*',n));if(['GroundOverlay','NetworkLink','Track','Model'].some(n=>all(doc,n).length))throw Error('This file contains overlays, network links, 3D models or tracks. Import a point/line-only KML to avoid losing those objects.');const fs=[];const placemarks=all(doc,'Placemark');const data=(pm,key)=>all(pm,'Data').find(d=>d.getAttribute('name')===key)?.getElementsByTagNameNS('*','value')[0]?.textContent;for(const pm of placemarks){const parent=data(pm,'lineSurveyParentRoute');if(parent&&placemarks.some(r=>r.getAttribute('id')===parent&&all(r,'LineString').length))continue;let vertexLabels=[];try{const v=JSON.parse(data(pm,'lineSurveyVertexLabels')||'[]');if(Array.isArray(v))vertexLabels=v}catch{}const name=all(pm,'name')[0]?.textContent||filename,description=all(pm,'description')[0]?.textContent||'';const geoms=[...pm.getElementsByTagName('*')].filter(el=>['Point','LineString','Polygon'].includes(el.localName));geoms.forEach((el,index)=>{if(g==='village'&&el.localName!=='Point')throw Error('Village-name imports must contain points only.');const coordNodes=el.localName==='Polygon'?[...all(el,'outerBoundaryIs'),...all(el,'innerBoundaryIs')].map(r=>all(r,'coordinates')[0]):[all(el,'coordinates')[0]];const ringLengths=coordNodes.map(n=>(n?.textContent?.trim()||'').split(/\s+/).filter(Boolean).length);const raw=coordNodes.map(n=>n?.textContent?.trim()||'').join(' ').trim();if(!raw)throw Error('A geometry has no coordinates.');const altMode=all(el,'altitudeMode')[0]?.textContent||'clampToGround';const points=raw.split(/\s+/).map(t=>{const a=t.split(',');if(a.length<2||a.slice(0,2).some(x=>!x.trim()))throw Error('Invalid coordinates in KML.');return {lon:Number(a[0]),lat:Number(a[1]),alt:a.length>2&&a[2]!==''?Number(a[2]):null,altMode}});if(el.localName==='LineString'&&vertexLabels.length===points.length)points.forEach((p,i)=>{if(typeof vertexLabels[i]==='string')p.label=vertexLabels[i]});fs.push({folderPath:KMLProjects.folderPath(pm),sourceColor:KMLProjects.color(doc,pm),style:KMLProjects.style(doc,pm),id:uid(),name:geoms.length>1?`${name} (${index+1})`:name,description,type:el.localName,altMode,group:g,points,...(el.localName==='Polygon'?{ringLengths}: {})})})}if(!fs.length)throw Error('No tower points or routes were found.');KMLProjects.matchLabels(fs);S.validate({...state,features:fs});return fs}
$('import').multiple=true;
$('import').onchange=async e=>{const files=Array.from(e.target.files);if(!files.length)return;try{const imported=[];for(const file of files){if(file.size>30*1024*1024)throw Error(file.name+': choose a file smaller than 30 MB.');let texts=[];if(file.name.toLowerCase().endsWith('.kmz')){const zip=await JSZip.loadAsync(await file.arrayBuffer());const entries=Object.values(zip.files).filter(f=>!f.dir&&f.name.toLowerCase().endsWith('.kml'));if(!entries.length)throw Error('KMZ contains no KML.');let total=0;for(const entry of entries){const text=await entry.async('string');total+=text.length;if(total>40e6)throw Error('Expanded KML is too large.');texts.push([text,entry.name])}}else texts=[[await file.text(),file.name]];const projectId=uid(),projectName=file.name.replace(/\.(kmz|kml)$/i,'');const fs=texts.flatMap(([t,n])=>parseKML(t,n,$('importgroup').value));fs.forEach(f=>Object.assign(f,{projectId,projectName}));imported.push(...fs)}S.validate({...state,features:[...state.features,...imported]});commit(()=>{state.features.push(...imported);selected=imported[0].id;if(state.name==='Untitled survey')state.name=imported[0].projectName});const ps=imported.flatMap(f=>f.points.map(p=>[p.lat,p.lon]));map.fitBounds(L.latLngBounds(ps),{padding:[45,45],maxZoom:17});toast(`Opened ${files.length} projects, ${imported.length} features.`)}catch(e){toast(e.message)}finally{$('import').value=''}};

function download(data,name,type){const url=URL.createObjectURL(new Blob([data],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),10000)}
function filename(){return state.name.replace(/[^\w\- ]/g,'_')||'survey'}function exportState(){const fs=state.features.filter(visible);if(!fs.length)throw Error('No visible layers to export.');return {...state,features:fs}}
$('backup').onclick=()=>download(JSON.stringify(state,null,2),filename()+'.survey.json','application/json');$('restore').onchange=async e=>{try{const f=e.target.files[0];if(!f)return;const next=S.validate(JSON.parse(await f.text()));if(state.features.length&&!confirm('Replace this project with the backup? You can Undo this change.'))return;commit(()=>{state=next;selected=null});fit()}catch(e){toast(e.message)}finally{e.target.value=''}};
$('kml').onclick=()=>{try{download(S.kml(exportState()),filename()+'.kml','application/vnd.google-earth.kml+xml');toast('KML exported with routes and named vertex points.')}catch(e){toast(e.message)}};
$('dxf').onclick=()=>{try{download(S.dxf(exportState()),filename()+`_UTM${state.zone}${state.hemisphere}.dxf`,'application/dxf');toast('DXF exported in WGS84 UTM metres. 2D drawing; source altitude stays in Excel/KML.')}catch(e){toast(e.message)}};
$('demo').onclick=()=>{commit(()=>{const coords=[[78.47,17.43],[78.474,17.434],[78.481,17.437],[78.486,17.443]];const route={id:uid(),name:'Sample 132 kV route',type:'LineString',group:'active',points:coords.map((p,i)=>({lon:p[0],lat:p[1],alt:null,label:'AP-'+String(i+1).padStart(2,'0')}))};state.features.push(route,{id:uid(),name:'Example village',type:'Point',group:'village',points:[{lon:78.479,lat:17.432,alt:null}]});selected=route.id;if(state.name==='Untitled survey')state.name='Sample transmission survey';state.zone=44;state.hemisphere='N'});fit();toast('Illustrative sample only — not real survey data.')};
$('gps').onclick=()=>{if(!navigator.geolocation)return toast('Location is unavailable on this device.');navigator.geolocation.getCurrentPosition(p=>{gpsLayer.clearLayers();L.circle([p.coords.latitude,p.coords.longitude],{radius:p.coords.accuracy,color:'#2878be'}).addTo(gpsLayer);map.setView([p.coords.latitude,p.coords.longitude],17);toast(`Phone GPS accuracy: ±${Math.round(p.coords.accuracy)} m. Location is not added as a survey point.`)},e=>toast('Location unavailable: '+e.message),{enableHighAccuracy:true,timeout:20000})};
$('help').onclick=()=>{modal('Using Line Survey',[],()=>{});$('fields').textContent='Import points and routes from KML/KMZ. Select a layer to edit coordinates or drag vertices. Use Move to layer to finalize and lock a project. The permanent AP village boundaries layer contains 18,100 source polygons, with mandal and district names matched to your supplied gazette. Unmatched records are flagged in Excel. Zoom in for boundary names. Excel uses those polygons to identify each vertex village even when the layer is hidden. Optional village-name points are separate annotations. Exports include visible survey layers; Excel excludes village-name point annotations. DXF is a 2D WGS84 UTM drawing in metres. Confirm your zone before export. KML exports geometry and descriptions, not original styles, attachments or folders. Back up regularly. Offline use needs the app cached once on this same browser. OSM and satellite imagery are online only; no tile downloads are included. Phone GPS is approximate.'};
map.on('mousemove',e=>$('position').textContent=e.latlng.lat.toFixed(5)+'°, '+e.latlng.lng.toFixed(5)+'°');
function network(){ $('offline').textContent=cacheReady?(navigator.onLine?'Ready for offline use':'Offline · ready'):(navigator.onLine?'Online · offline cache pending':'Offline · cache not verified')};window.addEventListener('online',network);window.addEventListener('offline',network);
if('serviceWorker'in navigator&&location.protocol!=='file:')navigator.serviceWorker.register('sw.js').then(()=>navigator.serviceWorker.ready).then(()=>{cacheReady=true;network()}).catch(()=>{$('offline').textContent='Offline setup unavailable'});else $('offline').textContent='Local files · use Start app for install';
window.addEventListener('storage',e=>{if(e.key==='line-survey-v1'&&e.newValue){try{state=S.validate(JSON.parse(e.newValue));history=[];redoHistory=[];editSession=null;if(mapPick){mapPick=null;pickingUI(false)}if($('dialog').open)$('dialog').close();render();toast('Project updated in another tab.')}catch{toast('Could not read a project update from another tab.')}}});
render();fit();if(state.features.length)$('saved').textContent='Restored from this device';
try{const background=localStorage.getItem('line-survey-background');if(['osm','satellite'].includes(background)){$('background').value=background;$('background').onchange()}}catch{}







