(function(root){
const esc=s=>String(s??'').replace(/[<>&"']/g,c=>({'<':'&lt;','>':'&gt;','&':'&amp;','"':'&quot;',"'":'&apos;'}[c]));
function valid(p){return Number.isFinite(p.lat)&&Number.isFinite(p.lon)&&p.lat>=-90&&p.lat<=90&&p.lon>=-180&&p.lon<=180&&(p.alt===null||Number.isFinite(p.alt))}
function validate(s){if(!s||!Array.isArray(s.features)||s.features.length>10000)throw Error('Invalid project file.');if(!Number.isInteger(s.zone)||s.zone<1||s.zone>60||!['N','S'].includes(s.hemisphere))throw Error('Choose a UTM zone from 1 to 60.');let ids=new Set();for(const f of s.features){if(!f.id||ids.has(f.id)||typeof f.name!=='string'||!['Point','LineString','Polygon'].includes(f.type)||!Array.isArray(f.points)||f.points.length<(f.type==='Point'?1:2)||f.points.length>100000||f.type==='Point'&&f.points.length!==1||!f.points.every(valid))throw Error('Project contains invalid or unsupported geometry.');if(f.type==='Polygon'){if(!Array.isArray(f.ringLengths)||f.ringLengths.some(n=>!Number.isInteger(n)||n<4)||f.ringLengths.reduce((a,b)=>a+b,0)!==f.points.length)throw Error('Invalid polygon rings.');for(const r of rings(f))if(r[0].lat!==r.at(-1).lat||r[0].lon!==r.at(-1).lon)throw Error('Polygon ring is not closed.')}ids.add(f.id)}return s}
function xy(p,s){if(p.lat < -80||p.lat>84)throw Error('UTM export supports latitudes from 80°S to 84°N.');if((p.lat<0&&s.hemisphere==='N')||(p.lat>0&&s.hemisphere==='S'))throw Error('A vertex is in the other hemisphere. Change the export hemisphere or separate the survey.');const center=s.zone*6-183;const delta=Math.abs(((p.lon-center+540)%360)-180);if(delta>6)throw Error('A vertex is over 6° from the selected UTM central meridian. Confirm the project zone.');return root.proj4('EPSG:4326',`+proj=utm +zone=${s.zone} ${s.hemisphere==='S'?'+south ':''}+datum=WGS84 +units=m +no_defs`,[p.lon,p.lat])}
function rings(f){let offset=0;return (f.ringLengths||[f.points.length]).map(n=>{const r=f.points.slice(offset,offset+n);offset+=n;return r})}
function vertexLabel(f,i){if(f.type==='Polygon'){let offset=0;for(const n of f.ringLengths){if(i===offset+n-1){i=offset;break}offset+=n}}return f.points[i].label||(f.type==='Point'?f.name:`V${i+1}`)}
function rows(s,metrics=true){validate(s);return s.features.flatMap(f=>{let prev=null,chain=0;return f.points.map((p,i)=>{if(f.type==='Polygon'&&f.ringLengths.slice(0,-1).reduce((a,n)=>{a.push((a.at(-1)||0)+n);return a},[0]).includes(i)){prev=null;chain=0}const [e,n]=metrics?xy(p,s):[null,null],span=metrics&&prev?Math.hypot(e-prev[0],n-prev[1]):0;chain+=span;prev=[e,n];return [f.name,f.type,i+1,vertexLabel(f,i),p.lat,p.lon,e,n,p.alt,span,chain,`WGS84 / UTM ${s.zone}${s.hemisphere}`,p.altMode||'unspecified']})})}
function kml(s){
 validate(s);
 const coords=p=>`${p.lon},${p.lat}${p.alt===null?'':','+p.alt}`;
 const features=s.features.map((f,fi)=>{
  const routeId=`survey-route-${fi}`,mode=esc(f.altMode||'clampToGround'),style=root.FeatureStyle?root.FeatureStyle.kml(f):'';
  const labels=f.type==='LineString'?`<ExtendedData><Data name="lineSurveyVertexLabels"><value>${esc(JSON.stringify(f.points.map(p=>p.label||'')))}</value></Data></ExtendedData>`:'';
  if(f.type==='Polygon')return `<Placemark><name>${esc(f.name)}</name><description>${esc(f.description||'')}</description>${style}<Polygon><altitudeMode>${mode}</altitudeMode>${rings(f).map((r,i)=>{const tag=i?'innerBoundaryIs':'outerBoundaryIs';return `<${tag}><LinearRing><coordinates>${r.map(coords).join(' ')}</coordinates></LinearRing></${tag}>`}).join('')}</Polygon></Placemark>`;
  const geometry=`<Placemark${f.type==='LineString'?` id="${routeId}"`:''}><name>${esc(f.name)}</name><description>${esc(f.description||'')}</description>${style}${labels}<${f.type}><altitudeMode>${mode}</altitudeMode><coordinates>${f.points.map(coords).join(' ')}</coordinates></${f.type}></Placemark>`;
  if(f.type!=='LineString')return geometry;
  const markers=f.points.map((p,i)=>`<Placemark><name>${esc(p.label||`${f.name} - V${i+1}`)}</name><description>${esc(`Route: ${f.name}; vertex ${i+1}`)}</description><styleUrl>#survey-vertex</styleUrl><ExtendedData><Data name="lineSurveyParentRoute"><value>${routeId}</value></Data></ExtendedData><Point><altitudeMode>${mode}</altitudeMode><coordinates>${coords(p)}</coordinates></Point></Placemark>`).join('');
  return `${geometry}<Folder><name>${esc(f.name)} — Vertex points</name><visibility>1</visibility>${markers}</Folder>`;
 }).join('');
 return `<?xml version="1.0" encoding="UTF-8"?><kml xmlns="http://www.opengis.net/kml/2.2"><Document><name>${esc(s.name)}</name><Style id="survey-vertex"><IconStyle><color>ff31a5ef</color><scale>0.8</scale></IconStyle><LabelStyle><scale>0.9</scale></LabelStyle></Style>${features}</Document></kml>`;
}
function dxf(s){validate(s);s={...s,features:s.features.flatMap(f=>f.type==='Polygon'?rings(f).map((r,i)=>({...f,name:f.name+' ring '+(i+1),type:'LineString',points:r})):f)};const a=[];const put=(...v)=>a.push(...v.map(String));put(0,'SECTION',2,'HEADER',9,'$ACADVER',1,'AC1009',9,'$MEASUREMENT',70,1,0,'ENDSEC',0,'SECTION',2,'ENTITIES');for(const f of s.features){const pts=f.points.map(p=>xy(p,s));if(f.type==='LineString'){put(0,'POLYLINE',8,'ROUTE',66,1,70,0,10,0,20,0,30,0);for(const p of pts)put(0,'VERTEX',8,'ROUTE',10,p[0],20,p[1],30,0);put(0,'SEQEND',8,'ROUTE')}pts.forEach((p,i)=>{put(0,'POINT',8,f.type==='Point'?'TOWERS':'VERTICES',10,p[0],20,p[1],30,0);put(0,'TEXT',8,'LABELS',10,p[0]+2,20,p[1]+2,30,0,40,2.5,1,(f.points[i].label|| (f.type==='Point'?f.name:`${f.name}-${i+1}`)).replace(/[\r\n]/g,' ').replace(/[^\x20-\x7E]/g,'?'))})}put(0,'ENDSEC',0,'EOF');return a.join('\r\n')+'\r\n'}
root.Survey={esc,valid,validate,xy,rows,kml,dxf,rings,vertexLabel};if(typeof module!=='undefined')module.exports=root.Survey;
})(typeof window==='undefined'?globalThis:window);
