/* Survey geometry, crossings and recoverable drawing drafts. */
(()=>{
 const R=6371000,rad=Math.PI/180;
 window.NVVArea=ps=>{if(ps.length<3)return 0;let sum=0;for(let i=0;i<ps.length;i++){const a=ps[i],b=ps[(i+1)%ps.length];let dl=(b.lon-a.lon)*rad;if(dl>Math.PI)dl-=2*Math.PI;if(dl< -Math.PI)dl+=2*Math.PI;sum+=dl*(2+Math.sin(a.lat*rad)+Math.sin(b.lat*rad))}return Math.abs(sum*R*R/2)};
 const draftKey='nvv-drawing-draft-v1';let pending;try{pending=JSON.parse(localStorage.getItem(draftKey))}catch{}
 window.NVVDraft={save:d=>{try{if(d.points?.length||d.center)localStorage.setItem(draftKey,JSON.stringify({...d,updated:Date.now()}))}catch{toast('Could not save drawing draft. Device storage may be full.')}},clear:()=>{try{localStorage.removeItem(draftKey)}catch{}}};
 const btn=(text,name,fn)=>{const b=document.createElement('button');b.type='button';b.textContent=text;b.title=name;b.setAttribute('aria-label',name);b.onclick=fn;return b};
 const circles=L.layerGroup().addTo(map);let circleMode=false,center=null,radius=100,editing=null;
 const hud=document.createElement('div');hud.className='draw-hud';hud.hidden=true;const hint=document.createElement('span'),input=document.createElement('input');input.type='number';input.min='0.01';input.max='1000000';input.step='any';input.style.width='95px';input.setAttribute('aria-label','Circle radius metres');input.oninput=()=>{const n=Number(input.value);if(n>0&&n<=1000000){radius=n;drawCircle()}};
 function destination(c,bearing,d){const p=c.lat*rad,l=c.lon*rad,a=d/R,t=bearing*rad;const lat=Math.asin(Math.sin(p)*Math.cos(a)+Math.cos(p)*Math.sin(a)*Math.cos(t)),lon=l+Math.atan2(Math.sin(t)*Math.sin(a)*Math.cos(p),Math.cos(a)-Math.sin(p)*Math.sin(lat));return {lat:lat/rad,lon:((lon/rad+540)%360)-180,alt:null}}
 function geometry(c,d){const ps=Array.from({length:120},(_,i)=>destination(c,i*3,d));ps.push({...ps[0]});return ps}
 function clearCircle(){circleMode=false;center=null;editing=null;hud.hidden=true;circles.clearLayers();NVVDraft.clear()}
 function drawCircle(){circles.clearLayers();if(!center){hint.textContent='Choose centre on map or an existing point';return}NVVDraft.save({mode:'Circle',center,radius,editing});hint.textContent='Radius '+radius.toFixed(2)+' m · Area '+(Math.PI*radius*radius).toFixed(2)+' m²';L.circle([center.lat,center.lon],{radius,color:'#167e97',interactive:false}).addTo(circles);const c=L.marker([center.lat,center.lon],{draggable:true,bubblingMouseEvents:false,title:'Circle centre'}).addTo(circles);c.on('dragend',()=>{const p=c.getLatLng();center={lat:p.lat,lon:p.lng,alt:null};drawCircle()});const edge=destination(center,90,radius),m=L.marker([edge.lat,edge.lon],{draggable:true,bubblingMouseEvents:false,title:'Circle radius',icon:L.divIcon({className:'map-select-vertex',html:'↔',iconSize:[32,32],iconAnchor:[16,16]})}).addTo(circles);m.on('dragend',()=>{radius=map.distance([center.lat,center.lon],m.getLatLng());input.value=radius.toFixed(2);drawCircle()})}
 function startCircle(id=null){window.NVVStopDrawing();window.NVVMeasurement?.clear();circleMode=true;editing=id;const f=state.features.find(f=>f.id===id);center=f?.circle?.center?{...f.circle.center}:null;radius=f?.circle?.radius||100;input.value=radius;hud.hidden=false;document.querySelector('#tools-panel').hidden=true;drawCircle()}
 hud.append(hint,input,document.createTextNode('m'),btn('Save','Save circle',()=>{if(!center||!(radius>0))return toast('Choose a centre and valid radius.');const circle={center:{...center},radius,area:Math.PI*radius*radius};if(editing){const id=editing;commit(()=>{const f=state.features.find(f=>f.id===id);f.circle=circle;f.points=geometry(center,radius);f.ringLengths=[f.points.length]});clearCircle();return}const f={id:uid(),name:'Circle',type:'Polygon',group:'active',circle,points:geometry(center,radius),ringLengths:[121]};window.NVVSaveFeature(f);$('dialog').addEventListener('close',()=>{if(state.features.some(x=>x.id===f.id))clearCircle()},{once:true})}),btn('×','Cancel circle',clearCircle));document.querySelector('main').append(hud);
 const acceptBefore=window.NVVAcceptPoint;window.NVVAcceptPoint=p=>{if(circleMode){center={lat:p.lat,lon:p.lon,alt:null};drawCircle();return true}if(crossingMode){placeCrossing(p);return true}return acceptBefore(p)};map.on('click',e=>{if($('dialog').open)return;if(circleMode){if(!center)center={lat:e.latlng.lat,lon:e.latlng.lng,alt:null};else{radius=map.distance([center.lat,center.lon],e.latlng);input.value=radius.toFixed(2)}drawCircle()}else if(crossingMode)placeCrossing({lat:e.latlng.lat,lon:e.latlng.lng,alt:null})});window.NVVCircleEdit=startCircle;
 const tray=document.querySelector('.drawing-buttons');tray.append(btn('◯','Draw Circle',()=>startCircle()));
 document.querySelector('.selected-actions').append(btn('Name','Rename selected point',()=>{const f=active();if(!f||locked())return toast('Select an editable feature.');modal('Feature name',[{id:'name',label:'Name',value:f.name,required:true}],v=>{const name=v.name.trim();if(!name)throw Error('Enter a name.');commit(()=>{f.name=name;if(f.type==='Point')f.points[0].label=name});if(editSession){history.push(editSession);redoHistory=[];editSession=null;persist();render()}})}));
 let crossingMode=false,crossingRoute=null;
 function crossingLocation(route,p){let best=null,chain=0;for(let i=1;i<route.points.length;i++){const a=route.points[i-1],b=route.points[i],cos=Math.cos(p.lat*rad),dx=(b.lon-a.lon)*cos,dy=b.lat-a.lat,px=(p.lon-a.lon)*cos,py=p.lat-a.lat,t=Math.max(0,Math.min(1,(dx*px+dy*py)/(dx*dx+dy*dy||1))),q={lat:a.lat+t*(b.lat-a.lat),lon:a.lon+t*(b.lon-a.lon),alt:null},distance=map.distance([p.lat,p.lon],[q.lat,q.lon]),length=map.distance([a.lat,a.lon],[b.lat,b.lon]);if(!best||distance<best.distance)best={point:q,distance,chainage:chain+map.distance([a.lat,a.lon],[q.lat,q.lon])};chain+=length}return best}
 window.NVVCrossingLocation=crossingLocation;
 function placeCrossing(p){crossingMode=false;const route=state.features.find(f=>f.id===crossingRoute);if(!route)return;const hit=crossingLocation(route,p);modal('Save crossing',[{id:'name',label:'Crossing name',required:true},{id:'type',label:'Type',value:'Road',options:['Road','Railway','River','Power line'].map(t=>[t,t])}],v=>{const name=v.name.trim();if(!name)throw Error('Enter a crossing name.');commit(()=>{state.features.push({id:uid(),name,type:'Point',group:'active',projectId:route.projectId,projectName:route.projectName,crossing:{routeId:route.id,type:v.type,chainage:hit.chainage},points:[{...hit.point,label:name}]})})});const note=document.createElement('p');note.textContent='On '+route.name+' · chainage '+hit.chainage.toFixed(2)+' m';$('fields').append(note)}
 const list=document.createElement('details');const summary=document.createElement('summary');summary.textContent='Crossings';list.append(summary);document.querySelector('#projects-panel').append(list);
 function refreshCrossings(){list.querySelectorAll(':scope > div').forEach(n=>n.remove());for(const f of state.features.filter(f=>f.crossing)){const route=state.features.find(r=>r.id===f.crossing.routeId);const hit=route?crossingLocation(route,f.points[0]):null;const row=document.createElement('div');row.className='project-feature';const text=document.createElement('span');text.textContent=(f.projectName||state.name)+' · '+f.crossing.type+' · '+f.name+' · '+(hit?hit.chainage.toFixed(2)+' m':'Route unavailable');row.append(text,btn('Open','Open crossing '+f.name,()=>{map.setView([f.points[0].lat,f.points[0].lon],18);select(f.id)}),btn('Edit','Edit crossing '+f.name,()=>modal('Edit crossing',[{id:'name',label:'Name',value:f.name,required:true},{id:'type',label:'Type',value:f.crossing.type,options:['Road','Railway','River','Power line'].map(t=>[t,t])}],v=>commit(()=>{f.name=v.name.trim();f.points[0].label=f.name;f.crossing.type=v.type}))),btn('Export','Export crossing '+f.name,()=>{select(f.id);document.querySelector('.selected-actions [aria-label="Export selected feature"]').click()}),btn('🗑','Delete crossing '+f.name,()=>{if(confirm('Delete '+f.name+'?'))commit(()=>{state.features=state.features.filter(x=>x.id!==f.id)})}));list.append(row)}}
 const oldRender=render;render=function(){oldRender();refreshCrossings()};refreshCrossings();
 tray.append(btn('╳','Mark crossing',()=>{window.NVVStopDrawing();window.NVVMeasurement?.clear();const routes=state.features.filter(f=>f.type==='LineString');if(!routes.length)return toast('Draw or import a route first.');modal('Choose crossing route',[{id:'route',label:'Route',value:active()?.type==='LineString'?selected:routes[0].id,options:routes.map(f=>[f.id,(f.projectName||state.name)+' · '+f.name])}],v=>{crossingRoute=v.route;crossingMode=true;document.querySelector('#tools-panel').hidden=true;toast('Tap the crossing location. It will snap onto the chosen route.')})}));
 document.addEventListener('survey-stop-tools',()=>{if(circleMode)clearCircle();crossingMode=false});
 document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!$('dialog').open){if(circleMode)clearCircle();crossingMode=false}});
 if(pending&&(pending.points?.length||pending.center)){setTimeout(()=>{modal('Unfinished drawing',[{id:'choice',label:'Drawing',value:'resume',options:[['resume','Resume'],['discard','Discard']]}],v=>{if(v.choice==='discard'){NVVDraft.clear();return}if(pending.mode==='Circle'){startCircle(pending.editing);center=pending.center;radius=pending.radius;input.value=radius;drawCircle()}else if(pending.mode==='Measurement')NVVMeasurement.resume(pending);else NVVResumeDrawing(pending)});$('cancel').textContent='Discard';const discard=()=>NVVDraft.clear();$('cancel').addEventListener('click',discard,{once:true});$('dialog').addEventListener('close',()=>{$('cancel').textContent='Cancel';$('cancel').removeEventListener('click',discard)},{once:true})},200)}
})();
