/* One workspace controller. Survey operations remain in the original app/core. */
(()=>{
 const main=document.querySelector('main'),aside=document.querySelector('aside'),bar=document.querySelector('.mapbar>.row');
 document.body.classList.add('field-layout');
 const panels={},switches={};
 function button(text,label,action){const b=document.createElement('button');b.type='button';b.textContent=text;b.title=label;b.setAttribute('aria-label',label);b.onclick=action;return b}
 function panel(key,title){const el=document.createElement('section');el.id=key+'-panel';el.className='field-panel';el.hidden=true;const head=document.createElement('div');head.className='panel-head';const h=document.createElement('h2');h.textContent=title;head.append(h,button('×','Close '+title,()=>show(null)));el.append(head);main.append(el);panels[key]=el;return el}
 function show(key){cancelEdit();for(const [k,p]of Object.entries(panels))p.hidden=k!==key;for(const [k,b]of Object.entries(switches))b.setAttribute('aria-expanded',String(k===key));$('editor').hidden=true}
 function toggle(k){show(panels[k].hidden?k:null)}
 function trigger(k,text,label,parent){const b=button(text,label,()=>toggle(k));b.setAttribute('aria-controls',panels[k].id);b.setAttribute('aria-expanded','false');switches[k]=b;parent.append(b);return b}
 const layers=panel('layers','Layers'),projects=panel('projects','My Projects'),imports=panel('import','Import'),exports=panel('export','Export');
 layers.append(controls);
 imports.append($('import').closest('label'),$('importgroup').closest('label'),$('restore').closest('label'));
 // Group switches apply to project data and belong in My Projects.
 for(const id of ['showactive','showfinal'])projects.append($(id).closest('label'));
 const projectName=document.createElement('label');projectName.textContent='Workspace name';projectName.append($('project'));projects.append(projectName);
 const tree=document.createElement('div');tree.id='project-tree';projects.append(tree);
 projects.append($('demo'),$('saved'));$('demo').hidden=true;const projectSearch=document.createElement('input');projectSearch.type='search';projectSearch.placeholder='Search projects or features';projectSearch.setAttribute('aria-label','Search My Projects');projects.insertBefore(projectSearch,tree);function filterProjects(){const q=projectSearch.value.trim().toLowerCase();for(const d of tree.children){d.hidden=!!q&&!d.textContent.toLowerCase().includes(q);for(const branch of d.querySelectorAll('details')){for(const row of branch.querySelectorAll('.project-feature'))row.hidden=!!q&&!row.textContent.toLowerCase().includes(q)&&!d.querySelector('summary').textContent.toLowerCase().includes(q);if(q&&[...branch.querySelectorAll('.project-feature')].some(r=>!r.hidden)){d.open=true;branch.open=true}}}}projectSearch.oninput=filterProjects;
 const exportSettings=document.createElement('div');exportSettings.className='export-settings';exportSettings.hidden=true;const projectionNote=document.createElement('p');projectionNote.className='projection-note';exports.append(projectionNote);
 for(const id of ['zone','hemisphere'])exportSettings.append($(id).closest('label'));
 exports.append(exportSettings,$('backup'));$('backup').textContent='Backup whole workspace';$('backup').title='Saves all projects and reference points, regardless of export selection';
 // Keep original export handlers available, without tray buttons for vertex/Excel export.
 const legacy=document.createElement('div');legacy.hidden=true;legacy.append($('features'),$('count'),$('newpoint'),$('newline'),document.querySelector('.exports'));main.append(legacy);aside.hidden=true;
 for(const node of [...aside.children])if(node!==controls)node.hidden=true;
 const left=L.control({position:'topleft'});left.onAdd=()=>{const el=L.DomUtil.create('div','left-stack');L.DomEvent.disableClickPropagation(el);L.DomEvent.disableScrollPropagation(el);const layersButton=trigger('layers','','Layers',el);layersButton.classList.add('layers-launcher');layersButton.innerHTML='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="m12 3 10 5-10 5L2 8z"/><path d="m3 12 9 5 9-5M3 16l9 5 9-5"/></svg>';trigger('projects','📁','My Projects',el);return el};left.addTo(map);
 $('undo').title='Undo';$('undo').setAttribute('aria-label','Undo');$('redo').title='Redo';$('redo').setAttribute('aria-label','Redo');
 bar.append($('undo'),$('redo'));trigger('import','↓','Import',bar);trigger('export','↑','Export',bar);bar.append($('fit'));$('fit').textContent='⛶';$('fit').title='Fit Survey';$('fit').setAttribute('aria-label','Fit Survey');
 const editor=$('editor');editor.hidden=true;editor.classList.add('field-editor');editor.querySelector('.editor-head').prepend(button('×','Close editor',()=>cancelEdit()));
 
 function cancelEdit(){stopVertexMap();editor.hidden=true;if(!editSession)return;state=JSON.parse(editSession);editSession=null;editor.hidden=true;render();}
 function saveEdit(){stopVertexMap();if(!editSession)return;try{S.validate(state);const original=editSession;editSession=null;if(JSON.stringify(state)!==original){history.push(original);redoHistory=[];}persist();editor.hidden=true;render();toast('Edits saved.')}catch(e){toast(e.message)}}
 const editActions=document.createElement('div');editActions.className='row edit-save-actions';editActions.append(button('Select vertex on map','Select vertex on map',()=>startVertexMap()),button('Cancel','Cancel feature edits',cancelEdit),button('Save','Save feature edits',saveEdit));editor.append(editActions);

 function cancelSelection(){cancelEdit();selected=null;render()}
 const selectedActions=document.createElement('div');selectedActions.className='selected-actions';selectedActions.hidden=true;const selectedName=document.createElement('span');selectedActions.append(selectedName,button('Edit','Edit selected feature',()=>openEdit(selected)),button('Export','Export selected feature',()=>openExport({feature:selected})));selectedActions.append(button('×','Cancel selected feature',cancelSelection));main.append(selectedActions);
 const kind=f=>f.type==='Point'?'Points':f.type==='Polygon'?'Areas':f.points.length===2?'Lines':'Polylines';
 const key=f=>f.projectId||'existing';
 const expanded=new Map();
 function details(id,title,open=false){const d=document.createElement('details');d.open=expanded.has(id)?expanded.get(id):open;const s=document.createElement('summary');s.textContent=title;d.append(s);d.ontoggle=()=>expanded.set(id,d.open);return d}
 function visibility(label,fs,property){const l=document.createElement('label');l.className='check';const c=document.createElement('input');c.type='checkbox';const n=fs.filter(f=>!f[property]).length;c.checked=n>0;c.indeterminate=n>0&&n<fs.length;c.setAttribute('aria-label','Show '+label);c.onchange=()=>commit(()=>fs.forEach(f=>f[property]=!c.checked));l.append(c,document.createTextNode(label));return l}
 function fitFeature(f){map.fitBounds(L.latLngBounds(f.points.map(p=>[p.lat,p.lon])),{padding:[60,60],maxZoom:18})}
 function openEdit(id){if(editSession&&selected===id){const f=active();if(f?.type==='LineString'||f?.type==='Polygon')startVertexMap();else editor.hidden=false;return}cancelEdit();const f=state.features.find(f=>f.id===id);if(!f)return;stopDrawing();show(null);selected=id;editSession=JSON.stringify(state);editor.hidden=f.type!=='Point';render();if(group(f)==='final')toast('Finalized project is locked. Use Move to layer to unlock it.');else if(f.type==='LineString'||f.type==='Polygon')startVertexMap();}
 let exportScope={};
 function scopeFeatures(){if(exportScope.feature)return state.features.filter(f=>f.id===exportScope.feature);if(exportScope.project)return state.features.filter(f=>key(f)===exportScope.project);return state.features.filter(f=>group(f)!=='village')}
 function exportSnapshot(fs){const points=fs.flatMap(f=>f.points);if(!points.length)return {...state,features:fs};const lat=(Math.min(...points.map(p=>p.lat))+Math.max(...points.map(p=>p.lat)))/2,lon=(Math.min(...points.map(p=>p.lon))+Math.max(...points.map(p=>p.lon)))/2;let zone=Math.min(60,Math.max(1,Math.floor((lon+180)/6)+1));if(lat>=56&&lat<64&&lon>=3&&lon<12)zone=32;if(lat>=72&&lat<84&&lon>=0&&lon<42)zone=lon<9?31:lon<21?33:lon<33?35:37;return {...state,features:fs,zone,hemisphere:lat<0?'S':'N'}}
 function updateExportCaption(){const fs=scopeFeatures(),projection=exportSnapshot(fs);projectionNote.textContent=fs.length?'DXF / Excel: WGS84 UTM '+projection.zone+projection.hemisphere+' · automatically selected from this export area. KML / KMZ use latitude and longitude.':'';exportCaption.textContent=fs.length?(exportScope.feature?fs[0].name:exportScope.project?fs[0].projectName||state.name:'All projects')+' · '+fs.length+' items':'No survey data';}
 function openExport(scope={}){exportScope=scope;show('export');exportProject.replaceChildren();const all=document.createElement('option');all.value='all';all.textContent='All projects';exportProject.append(all);const available=new Map();for(const f of state.features)if(group(f)!=='village')available.set(key(f),f.projectName||state.name);let i=0;for(const [id,name]of available){const o=document.createElement('option');o.value='project:'+i++;o.textContent=name;o.dataset.project=id;exportProject.append(o)}if(scope.feature){const f=state.features.find(x=>x.id===scope.feature);if(f){const o=document.createElement('option');o.value='feature';o.dataset.feature=f.id;o.textContent='Selected feature · '+f.name;exportProject.append(o);exportProject.value='feature'}}else if(scope.project){exportProject.value=[...exportProject.options].find(o=>o.dataset.project===scope.project)?.value||'all'}else exportProject.value='all';updateExportCaption();}
 const exportProjectLabel=document.createElement('label');exportProjectLabel.textContent='Project to export';const exportProject=document.createElement('select');exportProject.id='export-project';exportProject.setAttribute('aria-label','Project to export');exportProjectLabel.append(exportProject);exports.insertBefore(exportProjectLabel,projectionNote);exportProject.onchange=()=>{const o=exportProject.selectedOptions[0];exportScope=o.dataset.project?{project:o.dataset.project}:o.dataset.feature?{feature:o.dataset.feature}:{};updateExportCaption()};
 const exportCaption=document.createElement('p');exports.insertBefore(exportCaption,exportSettings);
 const exportRow=document.createElement('div');exportRow.className='row';exports.insertBefore(exportRow,exportSettings);
 for(const format of ['kml','dxf'])exportRow.append(button(format.toUpperCase(),'Export '+format.toUpperCase(),()=>{try{const fs=scopeFeatures();if(!fs.length)throw Error('Import or draw a feature first.');const s=JSON.parse(JSON.stringify(exportSnapshot(fs)));const name=(fs[0].projectName||state.name)+(fs.length===1?' - '+fs[0].name:'');download(format==='kml'?S.kml(s):S.dxf(s),name.replace(/[^\w\- ]/g,'_')+'.'+format,format==='kml'?'application/vnd.google-earth.kml+xml':'application/dxf');toast('Exported '+fs.length+' item(s).')}catch(e){toast(e.message)}}));
 
 exportRow.append(button('KMZ','Export KMZ',async()=>{try{const fs=scopeFeatures();if(!fs.length)throw Error('No data to export.');const snapshot=JSON.parse(JSON.stringify(exportSnapshot(fs))),zip=new JSZip();zip.file('doc.kml',S.kml(snapshot));download(await zip.generateAsync({type:'uint8array'}),(fs[0].projectName||state.name)+'.kmz','application/vnd.google-earth.kmz');toast('KMZ exported.')}catch(e){toast(e.message)}}));
 exportRow.append(button('Excel','Export Excel',async()=>{try{const fs=scopeFeatures();if(!fs.length)throw Error('No data to export.');const s=JSON.parse(JSON.stringify({...exportSnapshot(fs),name:fs[0].projectName||state.name}));toast('Preparing Excel…');const index=await APBoundaries.ensure(),districts=await APDistricts.ensure(),wb=await buildVertexWorkbook(s,index,APBoundaries.metadata,districts);download(await wb.xlsx.writeBuffer(),s.name+'.xlsx','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');toast('Excel exported.')}catch(e){toast(e.message)}}));

 switches.export.onclick=()=>{if(exports.hidden)openExport();else show(null)};
 let treeSignature='';const originalRender=render;
 render=function(){originalRender();const signature=state.name+'|'+state.features.map(f=>[f.id,f.name,f.projectId,f.projectName,f.type,f.points.length,f.hidden,f.projectHidden,f.group,f.folderPath,(f.hiddenFolders||[]).join(',')].join('~')).join('|');if(signature!==treeSignature){treeSignature=signature;tree.replaceChildren();const groups=new Map();for(const f of state.features)if(group(f)!=='village'){if(!groups.has(key(f)))groups.set(key(f),[]);groups.get(key(f)).push(f)}
 if(!groups.size){const p=document.createElement('p');p.className='muted';p.textContent='Import KML/KMZ or draw a feature to create a project.';tree.append(p)}
 for(const [id,fs]of groups){const name=fs[0].projectName||state.name,d=details(id,name,groups.size===1);const projectToggle=button(fs.some(f=>!f.projectHidden)?'On':'Off','Show project '+name,()=>{const off=fs.some(f=>!f.projectHidden);commit(()=>{fs.forEach(f=>f.projectHidden=off);if(off&&fs.some(f=>f.id===selected))selected=null})});projectToggle.className='project-toggle';projectToggle.setAttribute('role','switch');projectToggle.setAttribute('aria-checked',String(fs.some(f=>!f.projectHidden)));projectToggle.addEventListener('click',e=>e.stopPropagation());d.querySelector('summary').append(projectToggle);const actions=document.createElement('div');actions.className='row';actions.append(button('Export project','Export project '+name,()=>openExport({project:id})),button('Delete','Delete project '+name,()=>{if(confirm('Delete project '+name+' and its '+fs.length+' features?'))commit(()=>{state.features=state.features.filter(f=>key(f)!==id);if(!active())selected=null})}));d.append(actions);
 const folderPaths=new Set();for(const f of fs){const parts=(f.folderPath||'').split(' / ').filter(Boolean);for(let n=1;n<=parts.length;n++)folderPaths.add(parts.slice(0,n).join(' / '))}if(folderPaths.size){const folders=details(id+'folders','Folders',false);for(const path of folderPaths){const subset=fs.filter(f=>f.folderPath===path||f.folderPath?.startsWith(path+' / ')),row=document.createElement('div');row.className='folder-visibility-row';const text=document.createElement('span');text.textContent=path;const on=subset.some(f=>!(f.hiddenFolders||[]).includes(path)),toggle=button(on?'On':'Off','Show folder '+path+' in '+name,()=>commit(()=>{for(const f of subset){const hidden=new Set(f.hiddenFolders||[]);if(on)hidden.add(path);else hidden.delete(path);f.hiddenFolders=[...hidden]}if(subset.some(f=>f.id===selected)&&on)selected=null}));toggle.className='project-toggle';toggle.setAttribute('role','switch');toggle.setAttribute('aria-checked',String(on));row.append(text,toggle);folders.append(row)}d.append(folders)}
 for(const category of ['Points','Lines','Polylines','Areas']){const subset=fs.filter(f=>kind(f)===category),branch=details(id+category,category+' ('+subset.length+')');for(const f of subset){const row=document.createElement('div');row.className='project-feature';row.append(visibility('',[f],'hidden'));const nameButton=button(f.name,'Open / Select '+f.name,()=>{stopDrawing();show(null);select(f.id);fitFeature(f)});nameButton.className='feature-name';row.append(nameButton);const action=document.createElement('div');action.className='feature-actions';action.append(button('Edit','Edit '+f.name,()=>openEdit(f.id)),button('Export','Export '+f.name,()=>openExport({feature:f.id})));row.append(action);branch.append(row)}d.append(branch)}tree.append(d)}
 filterProjects();}const f=active();selectedActions.hidden=!f||!visible(f);selectedName.textContent=f?.name||'';
 };render();
 // Hybrid is the initial background; provider selection is stored locally.
 const googleSatellite=L.tileLayer('https://mt1.google.com/vt/lyrs=s&x={x}&y={y}&z={z}',{maxZoom:20,attribution:'Imagery © Google'}),googleHybrid=L.tileLayer('https://mt1.google.com/vt/lyrs=y&x={x}&y={y}&z={z}',{maxZoom:20,attribution:'Map data and imagery © Google'});
 const arcgisPlaces=L.tileLayer('https://services.arcgisonline.com/ArcGIS/rest/services/Reference/World_Boundaries_and_Places/MapServer/tile/{z}/{y}/{x}',{maxZoom:20,maxNativeZoom:19,attribution:'Labels © Esri'}),arcgisRoads=L.tileLayer('https://services.arcgisonline.com/ArcGIS/rest/services/Reference/World_Transportation/MapServer/tile/{z}/{y}/{x}',{maxZoom:20,maxNativeZoom:19,attribution:'Roads © Esri'}),arcgisHybrid=L.layerGroup([satellite,arcgisRoads,arcgisPlaces]);
 const background=$('background');background.replaceChildren();for(const [value,title]of [['arcgis-hybrid','ArcGIS Imagery Hybrid'],['hybrid','Google Hybrid'],['google-satellite','Google Satellite'],['osm','OpenStreetMap'],['plain','Plain · offline']]){const o=document.createElement('option');o.value=value;o.textContent=title;background.append(o)}
 background.onchange=()=>{for(const l of [osm,satellite,googleSatellite,googleHybrid,arcgisHybrid])map.removeLayer(l);const l={'arcgis-hybrid':arcgisHybrid,hybrid:googleHybrid,'google-satellite':googleSatellite,satellite,osm}[background.value];if(l)l.addTo(map);try{localStorage.setItem('line-survey-background',background.value)}catch{}};
 try{const saved=localStorage.getItem('line-survey-background');const migrated=localStorage.getItem('nvv-arcgis-default')==='1';background.value=migrated&&['arcgis-hybrid','hybrid','google-satellite','osm','plain'].includes(saved)?saved:'arcgis-hybrid';localStorage.setItem('nvv-arcgis-default','1')}catch{background.value='arcgis-hybrid'}background.onchange();
 // One uniformly spaced right-side stack: North, GPS, Tools.
 const toolHost=document.querySelector('.survey-tools'),oldTools=[...toolHost.children],tools=panel('tools','Tools / Drawing');tools.classList.add('right-panel');
 const north=button('','North / map rotation',()=>{if(!suppressNorthClick)map.setBearing(0);suppressNorthClick=false});north.classList.add('compass-control');
 const northHeading=document.createElement('span');northHeading.className='north-heading';northHeading.textContent='N';const northArrow=document.createElement('span');northArrow.className='north-arrow';northArrow.textContent='▲';const northDegrees=document.createElement('span');northDegrees.className='north-degrees';north.append(northHeading,northArrow,northDegrees);
 function updateCompass(){const degree=((map.getBearing()%360)+360)%360;northDegrees.textContent=Math.round(degree)%360+'°';northArrow.style.transform='rotate('+(-degree)+'deg)';north.title='Drag to rotate · tap N to reset · '+northDegrees.textContent;}
 let compassDrag=null,suppressNorthClick=false;
 north.onpointerdown=e=>{if(e.button!==0)return;e.preventDefault();e.stopPropagation();suppressNorthClick=false;compassDrag={id:e.pointerId,x:e.clientX,y:e.clientY,bearing:map.getBearing(),moved:false};north.setPointerCapture(e.pointerId)};
 north.onpointermove=e=>{if(!compassDrag||compassDrag.id!==e.pointerId)return;const delta=e.clientX-compassDrag.x+compassDrag.y-e.clientY;if(Math.abs(e.clientX-compassDrag.x)+Math.abs(e.clientY-compassDrag.y)>4)compassDrag.moved=true;if(compassDrag.moved){e.preventDefault();map.setBearing(((Math.round(compassDrag.bearing+delta)%360)+360)%360)}};
 north.onpointerup=e=>{if(!compassDrag)return;suppressNorthClick=compassDrag.moved;compassDrag=null;north.releasePointerCapture(e.pointerId)};
 north.onpointercancel=()=>{compassDrag=null;suppressNorthClick=true};
 north.onkeydown=e=>{if(['ArrowLeft','ArrowDown','ArrowRight','ArrowUp','Home'].includes(e.key)){e.preventDefault();map.setBearing(e.key==='Home'?0:((map.getBearing()+(['ArrowRight','ArrowUp'].includes(e.key)?1:-1))%360+360)%360)}};
 map.on('rotate',updateCompass);updateCompass();
 const gps=$('gps');gps.textContent='⌖';gps.title='My Location';gps.setAttribute('aria-label','My Location');gps.setAttribute('aria-pressed','false');
 let watchId=null,gpsPosition=null,firstFix=true;
 function saveGPS(){if(!gpsPosition)return;const p={lat:gpsPosition.coords.latitude,lon:gpsPosition.coords.longitude,alt:null};modal('Save GPS point',[{id:'name',label:'Point name',required:true}],v=>{const name=v.name.trim();if(!name)throw Error('Enter a point name.');const f={id:uid(),name,type:'Point',group:'active',points:[{...p,label:name}]},ref=active()||state.features.find(x=>group(x)!=='village');f.projectId=ref?.projectId||'manual:'+(state.name==='Untitled survey'?'GPS survey':state.name);f.projectName=ref?.projectName|| (state.name==='Untitled survey'?'GPS survey':state.name);commit(()=>{state.features.push(f);selected=f.id});gpsLayer.closePopup?.();show(null);toast('GPS point saved.');})}
 function located(p){gpsPosition=p;const {latitude:lat,longitude:lon,accuracy}=p.coords;gpsLayer.clearLayers();L.circle([lat,lon],{radius:accuracy,color:'#2878be',fillOpacity:0.1,interactive:false}).addTo(gpsLayer);const dot=L.circleMarker([lat,lon],{radius:9,color:'#fff',weight:3,fillColor:'#2878be',fillOpacity:1}).addTo(gpsLayer);const popup=document.createElement('div');const text=document.createElement('p');text.textContent='Accuracy ±'+Math.round(accuracy)+' m';popup.append(text,button('Save','Save GPS point',saveGPS));dot.bindPopup(popup);if(firstFix){map.setView([lat,lon],17);firstFix=false}gps.title='My Location · accuracy ±'+Math.round(accuracy)+' m';}
 function locateError(e){if(watchId!==null)navigator.geolocation.clearWatch(watchId);watchId=null;gps.setAttribute('aria-pressed','false');toast('Location unavailable: '+e.message)}
 gps.onclick=()=>{cancelEdit();if(watchId!==null){navigator.geolocation.clearWatch(watchId);watchId=null;gpsLayer.clearLayers();gps.setAttribute('aria-pressed','false');gps.title='My Location';return}if(!navigator.geolocation)return toast('Location unavailable.');firstFix=true;gps.setAttribute('aria-pressed','true');watchId=navigator.geolocation.watchPosition(located,locateError,{enableHighAccuracy:true,timeout:20000,maximumAge:0});toast('GPS tracking on. Tap the blue dot to save a point.');};
 function symbol(b,path){b.innerHTML='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="'+path+'"/></svg>';b.classList.add('symbol-tool');if(!b.hasAttribute('aria-label'))b.setAttribute('aria-label',b.title);return b}
 const paths={measure:'M3 17 17 3l4 4L7 21z M7 13l3 3m1-7 3 3m1-7 3 3',clear:'M3 6h18M9 6V3h6v3M6 6l1 15h10l1-15M10 10v7m4-7v7',edit:'m4 16 12-12 4 4L8 20H4z M13 7l4 4',vertex:'M3 12h18M12 3v18',Point:'M12 3a5 5 0 0 0-5 5c0 4 5 13 5 13s5-9 5-13a5 5 0 0 0-5-5z M12 7v2',Line:'M4 20 20 4M2 18h4v4H2zM18 2h4v4h-4z',Polyline:'M3 19 9 6l7 11 5-13M2 18h2v2H2zM8 5h2v2H8zM15 16h2v2h-2z',Area:'M3 17 7 4l13 3-3 14z'};
 const editTools=panel('edit-tools','Edit');editTools.classList.add('right-panel','symbol-tray');tools.classList.add('symbol-tray');tools.querySelector('h2').textContent='Measure / Draw';
 toolHost.replaceChildren(north,gps);symbol(trigger('tools','','Tools / Drawing',toolHost),'M3 18 8 5l7 10 6-12M2 17h2v2H2zM7 4h2v2H7zM14 14h2v2h-2zM20 2h2v2h-2z');symbol(trigger('edit-tools','','Edit tools',toolHost),paths.edit);
 const drawSection=document.createElement('div');drawSection.className='drawing-buttons';tools.append(drawSection);
 for(const node of oldTools){if(node.tagName!=='BUTTON'){tools.append(node);continue}if(node.title==='Show current location')continue;
 if(node.title==='Edit the selected point or route'){continue;}
 else if(node.title==='Add a vertex to the selected route'){node.onclick=()=>{const f=active();if(!f||f.type==='Point')return toast('Select a line, polyline or area first.');openEdit(f.id);if(!locked())startVertexMap()};editTools.append(symbol(node,paths.vertex));}
 else{const action=node.onclick;node.onclick=()=>{if(drawMode)stopDrawing();action();show(null)};drawSection.append(symbol(node,node.title==='Clear measured points'?paths.clear:paths.measure));}}

 // Survey distances use geodesic metres; deviation is the turn from a straight continuation.
 function routeBearing(a,b){const rad=Math.PI/180,p=a.lat*rad,q=b.lat*rad,d=(b.lon-a.lon)*rad;return Math.atan2(Math.sin(d)*Math.cos(q),Math.cos(p)*Math.sin(q)-Math.sin(p)*Math.cos(q)*Math.cos(d))/rad}
 function deviation(a,b,c){if(map.distance([a.lat,a.lon],[b.lat,b.lon])<.01||map.distance([b.lat,b.lon],[c.lat,c.lon])<.01)return null;const incoming=routeBearing(b,a)+180,outgoing=routeBearing(b,c);return ((outgoing-incoming+540)%360)-180}
 function angleDMS(value){const seconds=Math.round(Math.abs(value)*3600),degrees=Math.floor(seconds/3600),minutes=Math.floor(seconds%3600/60);return degrees+'° '+String(minutes).padStart(2,'0')+'′ '+String(seconds%60).padStart(2,'0')+'″'}
 function routeMetrics(points,layer){let total=0;const bounds=map.getBounds().pad(.1);for(let i=1;i<points.length;i++){const a=points[i-1],b=points[i],distance=map.distance([a.lat,a.lon],[b.lat,b.lon]);total+=distance;const x=map.latLngToContainerPoint([a.lat,a.lon]),y=map.latLngToContainerPoint([b.lat,b.lon]),mid=map.containerPointToLatLng(x.add(y).divideBy(2));if(bounds.contains(mid)&&x.distanceTo(y)>65){let angle=Math.atan2(y.y-x.y,y.x-x.x)*180/Math.PI;if(angle>90)angle-=180;if(angle< -90)angle+=180;const box=document.createElement('span');box.className='route-distance';box.textContent=distance.toFixed(2)+' m';box.style.transform='translate(-50%, -50%) rotate('+angle+'deg)';L.marker(mid,{interactive:false,icon:L.divIcon({className:'route-metric-anchor',html:box.outerHTML,iconSize:[0,0]})}).addTo(layer)}if(i<points.length-1&&bounds.contains([b.lat,b.lon])){const turn=deviation(a,b,points[i+1]);if(turn!==null)L.tooltip({permanent:true,direction:'right',offset:[20,0],className:'route-angle',interactive:false}).setLatLng([b.lat,b.lon]).setContent(angleDMS(turn)+' '+(Math.round(Math.abs(turn)*3600)===0?'Straight':turn<0?'LT':'RT')).addTo(layer)}}if(points.length>1){const last=points[points.length-1];if(bounds.contains([last.lat,last.lon]))L.tooltip({permanent:true,direction:'bottom',offset:[0,20],className:'route-total',interactive:false}).setLatLng([last.lat,last.lon]).setContent('Total '+total.toFixed(2)+' m').addTo(layer)}}
 window.NVVRouteMetrics=routeMetrics;
 let drawMode=null,drawPoints=[],drawChoice=null,drawInsert=false;const preview=L.layerGroup().addTo(map),drawStatus=document.createElement('p');drawStatus.className='muted';tools.append(drawStatus);
 function stopDrawing(){drawMode=null;drawPoints=[];drawChoice=null;drawInsert=false;preview.clearLayers();drawStatus.textContent='';saveDraw.hidden=cancelDraw.hidden=true;drawHUD.hidden=true;if(typeof drawAfter!=='undefined')drawAfter.hidden=drawRemove.hidden=true;document.dispatchEvent(new Event('survey-stop-tools'))}
 function begin(mode){stopDrawing();show(null);drawMode=mode;drawStatus.textContent='Tap map to draw '+mode.toLowerCase()+'.';saveDraw.hidden=mode==='Point';cancelDraw.hidden=false;drawHUD.hidden=false;hudText.textContent=drawStatus.textContent;}
 for(const [mode,label]of [['Point','Point'],['Line','Line'],['Polyline','Polyline'],['Area','Area']])drawSection.append(symbol(button('','Draw '+label,()=>begin(mode)),paths[mode]));
 const drawHUD=document.createElement('div');drawHUD.className='draw-hud';drawHUD.hidden=true;const hudText=document.createElement('span');drawHUD.append(hudText);main.append(drawHUD);
 const saveDraw=button('Save','Save drawing',()=>{const min=drawMode==='Area'?3:2;if(drawPoints.length<min)return toast('Choose at least '+min+' points.');const points=drawPoints.map(p=>({...p}));const area=drawMode==='Area';if(area)points.push({...points[0]});const feature={id:uid(),name:drawMode,type:area?'Polygon':'LineString',group:'active',points,...(area?{ringLengths:[points.length]}:{})};saveFeatureDialog(feature)}),cancelDraw=button('Cancel','Cancel drawing',()=>{stopDrawing();drawHUD.hidden=true});drawHUD.append(button('↶','Undo last drawing point',()=>{if(!drawMode||!drawPoints.length)return;drawPoints.pop();drawChoice=null;drawInsert=false;refreshDrawing()}),saveDraw,cancelDraw);saveDraw.hidden=cancelDraw.hidden=true;
 function destinationFields(){const list=new Map();for(const f of state.features)if(group(f)!=='village')list.set(key(f),f.projectName||state.name);return [{id:'destination',label:'Project',value:active()?key(active()):list.size===1?[...list.keys()][0]:'new',options:[...list].concat([['new','Create new project']])},{id:'projectName',label:'New project name',value:list.size?'':state.name==='Untitled survey'?'Field survey':state.name}]}
 function assignProject(f,v){if(v.destination==='new'){if(!v.projectName.trim())throw Error('Enter a project name.');f.projectId=uid();f.projectName=v.projectName.trim()}else{const ref=state.features.find(x=>key(x)===v.destination);if(!ref)throw Error('Choose a project.');f.projectId=ref.projectId;f.projectName=ref.projectName||state.name}return f}

 const drawAfter=button('+ After','Insert after drawing vertex',()=>{drawInsert=true;hudText.textContent='Tap map to insert after V'+(drawChoice+1)}),drawRemove=button('Remove','Remove drawing vertex',()=>{if(drawChoice===null)return;drawPoints.splice(drawChoice,1);drawChoice=null;drawInsert=false;refreshDrawing()});drawHUD.insertBefore(drawAfter,saveDraw);drawHUD.insertBefore(drawRemove,saveDraw);drawAfter.hidden=drawRemove.hidden=true;
 function refreshDrawing(){preview.clearLayers();drawAfter.hidden=drawRemove.hidden=drawChoice===null;hudText.textContent=drawMode+' · '+drawPoints.length+' points · drag a vertex to adjust';L.polyline(drawPoints.map(p=>[p.lat,p.lon]),{color:'#167e97',interactive:false}).addTo(preview);drawPoints.forEach((p,i)=>{const node=document.createElement('span');node.textContent='V'+(i+1);const marker=L.marker([p.lat,p.lon],{draggable:true,bubblingMouseEvents:false,title:'Drawing vertex '+(i+1),icon:L.divIcon({className:'map-select-vertex'+(drawChoice===i?' chosen-vertex':''),html:node.outerHTML,iconSize:[32,32],iconAnchor:[16,16]})}).addTo(preview);marker.on('click',e=>{if(e.originalEvent)L.DomEvent.stopPropagation(e.originalEvent);drawChoice=i;drawInsert=false;refreshDrawing();hudText.textContent='V'+(i+1)+' selected · drag, insert or remove'});marker.on('dragend',()=>{const ll=marker.getLatLng();p.lat=ll.lat;p.lon=ll.lng;drawChoice=i;refreshDrawing()})});if(drawMode!=='Area')routeMetrics(drawPoints,preview)}

 let saveMapPoint=null,saveLayoutFrame=null;
 function layoutSaveSheet(){cancelAnimationFrame(saveLayoutFrame);saveLayoutFrame=requestAnimationFrame(()=>{const dialog=$('dialog');if(!dialog.open||!dialog.classList.contains('feature-save-dialog')||!saveMapPoint)return;const view=window.visualViewport,height=view?.height||window.innerHeight,top=view?.offsetTop||0;const mapBox=map.getContainer().getBoundingClientRect();const reserve=Math.max(top+70,mapBox.top+70);dialog.style.maxHeight=Math.max(150,height+top-reserve-12)+'px';dialog.style.bottom='auto';dialog.style.top='0px';const sheetHeight=dialog.getBoundingClientRect().height;const sheetTop=Math.max(top+8,top+height-sheetHeight-8);dialog.style.top=sheetTop+'px';map.invalidateSize({pan:false});const screen=map.latLngToContainerPoint(saveMapPoint),targetY=(Math.max(mapBox.top,top)+sheetTop)/2-mapBox.top;map.panBy([screen.x-map.getSize().x/2,screen.y-targetY],{animate:false});})}
 window.visualViewport?.addEventListener('resize',layoutSaveSheet);window.visualViewport?.addEventListener('scroll',layoutSaveSheet);window.addEventListener('resize',layoutSaveSheet);$('dialog').addEventListener('focusin',layoutSaveSheet);$('dialog').addEventListener('close',()=>{saveMapPoint=null;for(const property of ['top','bottom','max-height'])$('dialog').style.removeProperty(property)});
 function saveFeatureDialog(f){$('dialog').classList.add('feature-save-dialog');modal('Save '+kind(f).toLowerCase(),[{id:'name',label:'Feature name',value:f.name,required:true},...destinationFields()],v=>{f.name=v.name.trim();if(!f.name)throw Error('Enter a name.');if(f.type==='Point')f.points[0].label=f.name;assignProject(f,v);commit(()=>{state.features.push(f);selected=f.id});stopDrawing();drawHUD.hidden=true;fitFeature(f)});const select=$('fields').querySelector('[name=destination]'),name=$('fields').querySelector('[name=projectName]');const update=()=>{name.parentElement.hidden=select.value!=='new';name.required=select.value==='new';layoutSaveSheet()};select.onchange=update;update();saveMapPoint=L.latLng(f.points[0].lat,f.points[0].lon);layoutSaveSheet()}
 function saveFeature(f){saveFeatureDialog(f)}
 window.saveSurveyPolyline=(points,kind,onSaved)=>{const f={id:uid(),name:kind,type:'LineString',group:'active',points,measurement:kind==='Measurement'};saveFeatureDialog(f);if(onSaved)$('dialog').addEventListener('close',()=>{if(state.features.some(x=>x.id===f.id))onSaved()},{once:true})};
 function addDrawingPoint(p){if(!drawMode||mapPick||$('dialog').open)return false;p={...p};if(drawMode==='Point'){preview.clearLayers();L.circleMarker([p.lat,p.lon],{radius:7,color:'#fff',weight:2,fillColor:'#167e97',fillOpacity:1,interactive:false}).addTo(preview);saveFeatureDialog({id:uid(),name:'Point',type:'Point',group:'active',points:[p]});return}if(drawMode==='Line'&&drawPoints.length===2)return toast('Tap Save.');if(drawInsert&&drawChoice!==null){drawPoints.splice(drawChoice+1,0,p);drawChoice++;drawInsert=false}else drawPoints.push(p);refreshDrawing();return true}
 window.NVVAcceptPoint=p=>drawMode?addDrawingPoint(p):window.NVVMeasurement?.accept(p)||false;
 map.on('click',e=>addDrawingPoint({lat:e.latlng.lat,lon:e.latlng.lng,alt:null}));
 let openingMapEdit=false;const previousSelect=select;select=function(id){if(!drawMode){if(editSession&&id!==selected)cancelEdit();previousSelect(id);const f=active();if(f?.type==='Point'&&!locked()&&!editSession){editSession=JSON.stringify(state);editor.hidden=true;render()}if(f?.type==='LineString'&&!locked()&&!editSession&&!openingMapEdit){openingMapEdit=true;try{openEdit(id)}finally{openingMapEdit=false}}}};
 // Map-based vertex insertion stays inside the current editing transaction.
 let vertexMapActive=false,vertexChoice=null,insertPending=false;const vertexMapLayer=L.layerGroup().addTo(map),vertexHUD=document.createElement('div');vertexHUD.className='draw-hud vertex-map-hud';vertexHUD.hidden=true;const vertexHint=document.createElement('span'),addAfter=button('+ After','Add after selected vertex',()=>{if(vertexChoice===null)return;insertPending=true;addAfter.disabled=true;vertexHint.textContent='Tap the map for the new vertex after V'+(vertexChoice+1)});vertexHUD.append(vertexHint,addAfter,button('Export','Export selected polyline',()=>openExport({feature:selected})),button('Save','Save map vertex edits',saveEdit),button('Cancel','Cancel map vertex edits',cancelEdit));main.append(vertexHUD);
 function stopVertexMap(){vertexMapActive=false;vertexChoice=null;insertPending=false;vertexMapLayer.clearLayers();vertexHUD.hidden=true}
 function refreshVertexMap(){vertexMapLayer.clearLayers();if(!vertexMapActive)return;const f=active();if(!f||locked()||!visible(f)){stopVertexMap();return}const viewport=map.getBounds().pad(.15);const closing=new Set();if(f.type==='Polygon'){let n=0;for(const size of f.ringLengths){n+=size;closing.add(n-1)}}f.points.forEach((p,i)=>{if(closing.has(i)||!viewport.contains([p.lat,p.lon]))return;const node=document.createElement('span');node.textContent='V'+(i+1);const marker=L.marker([p.lat,p.lon],{bubblingMouseEvents:false,draggable:true,keyboard:true,title:'Select vertex '+(i+1),icon:L.divIcon({className:'map-select-vertex'+(vertexChoice===i?' chosen-vertex':''),html:node.outerHTML,iconSize:[32,32],iconAnchor:[16,16]})}).addTo(vertexMapLayer);marker.on('dragend',()=>{const ll=marker.getLatLng();vertexChoice=i;commit(()=>{p.lat=ll.lat;p.lon=((ll.lng+180)%360+360)%360-180;if(f.type==='Polygon'){let start=0;for(const size of f.ringLengths){if(i===start)Object.assign(f.points[start+size-1],p);start+=size}}});vertexHint.textContent='V'+(i+1)+' moved · Save to keep changes';addAfter.disabled=false;refreshVertexMap()});marker.on('click',e=>{if(e.originalEvent)L.DomEvent.stopPropagation(e.originalEvent);vertexChoice=i;insertPending=false;addAfter.disabled=false;vertexHint.textContent='V'+(i+1)+' selected · tap + After';refreshVertexMap()})});if(f.type==='LineString')routeMetrics(f.points,vertexMapLayer)}
 function startVertexMap(){const f=active();if(!f||f.type==='Point')return toast('Select a line, polyline or area first.');if(locked())return toast('Move this feature to Working survey before editing.');if(!editSession){openEdit(f.id)}vertexMapActive=true;vertexChoice=null;insertPending=false;editor.hidden=true;vertexHUD.hidden=false;addAfter.disabled=true;vertexHint.textContent='Tap the vertex you want to insert after';if(f.points.filter(p=>map.getBounds().contains([p.lat,p.lon])).length>400){const p=f.points[0];map.setView([p.lat,p.lon],17);toast('Zoomed to the first vertices. Pan along the route to edit others.')}refreshVertexMap()}
 const renderBeforeVertexMap=render;render=function(){renderBeforeVertexMap();refreshVertexMap()};
 let mapRefreshTimer;map.on('moveend',()=>{clearTimeout(mapRefreshTimer);mapRefreshTimer=setTimeout(()=>{renderMap(true);refreshVertexMap();if(drawMode&&drawMode!=='Point')refreshDrawing()},120)});
 map.on('click',e=>{if(!vertexMapActive||!insertPending||vertexChoice===null)return;const f=active();if(!f||locked())return;const at=vertexChoice+1,p={lat:e.latlng.lat,lon:((e.latlng.lng+180)%360+360)%360-180,alt:null};insertPending=false;commit(()=>{if(f.type==='Polygon'){let offset=0;for(let r=0;r<f.ringLengths.length;r++){const end=offset+f.ringLengths[r];if(vertexChoice<end){f.ringLengths[r]++;break}offset=end}}f.points.splice(at,0,p)});vertexChoice=at;addAfter.disabled=false;vertexHint.textContent='New V'+(at+1)+' inserted · Save to keep changes';refreshVertexMap()});
 // Place search, kept separate from the five top map actions.
 const searchForm=document.createElement('form');searchForm.className='place-search';const searchInput=document.createElement('input');searchInput.type='search';searchInput.placeholder='Search place or coordinates';searchInput.setAttribute('aria-label','Place search');const searchResults=document.createElement('div');searchResults.className='search-results';searchResults.hidden=true;searchForm.append(searchInput,button('⌕','Search place',()=>searchForm.requestSubmit()),searchResults);document.querySelector('header').append(searchForm);
 let searchRequest,searchTimer,searchSequence=0,lastSearchStarted=0;const searchCache=new Map();searchInput.autocomplete='off';searchInput.setAttribute('aria-expanded','false');searchResults.id='place-suggestions';searchInput.setAttribute('aria-controls',searchResults.id);
 function hideSuggestions(){searchResults.hidden=true;searchInput.setAttribute('aria-expanded','false')}
 function placeLine(place){const a=place.properties||{},name=a.name||a.city||a.locality||a.street||'Place',district=a.county||a.district||'District unavailable',postcode=a.postcode;return name+' · '+district+(postcode?' · '+postcode:'')}
 function renderSuggestions(results){searchResults.replaceChildren();searchResults.hidden=false;searchInput.setAttribute('aria-expanded','true');if(!results.length)searchResults.textContent='No places found.';for(const place of results.slice(0,5)){const label=placeLine(place);searchResults.append(button(label,'Open '+label,()=>{const [lon,lat]=place.geometry.coordinates;const extent=place.properties?.extent;if(extent?.length===4)map.fitBounds([[extent[1],extent[0]],[extent[3],extent[2]]],{maxZoom:17});else map.setView([lat,lon],16);hideSuggestions();searchInput.value=label;searchSequence++;if(searchRequest)searchRequest.abort()}))}}
 async function searchPlaces(sequence){const q=searchInput.value.trim();if(q.length<2){hideSuggestions();return}const coordinate=q.match(/^(-?\d+(?:\.\d+)?)\s*,\s*(-?\d+(?:\.\d+)?)$/);if(coordinate){const lat=Number(coordinate[1]),lon=Number(coordinate[2]);if(!S.valid({lat,lon,alt:null}))return toast('Enter valid latitude, longitude.');map.setView([lat,lon],17);hideSuggestions();return}if(searchCache.has(q.toLowerCase())){renderSuggestions(searchCache.get(q.toLowerCase()));return}if(searchRequest)searchRequest.abort();searchRequest=new AbortController();const request=searchRequest;searchResults.hidden=false;searchInput.setAttribute('aria-expanded','true');searchResults.textContent='Searching…';lastSearchStarted=Date.now();try{const center=map.getCenter();let results;try{const r=await fetch('https://geocode.arcgis.com/arcgis/rest/services/World/GeocodeServer/findAddressCandidates?f=json&outSR=4326&forStorage=false&maxLocations=5&outFields=PlaceName,City,Subregion,Postal&location='+center.lng+','+center.lat+'&SingleLine='+encodeURIComponent(q),{signal:request.signal});if(!r.ok)throw Error('Search service unavailable');const response=await r.json();if(response.error)throw Error('Search service unavailable');results=(response.candidates||[]).slice(0,5).map(c=>({geometry:{type:'Point',coordinates:[c.location.x,c.location.y]},properties:{name:c.attributes?.PlaceName||c.attributes?.City||c.address.split(',')[0],county:c.attributes?.Subregion,postcode:c.attributes?.Postal,extent:c.extent?[c.extent.xmin,c.extent.ymin,c.extent.xmax,c.extent.ymax]:undefined}}))}catch(error){if(error.name==='AbortError')throw error;const r=await fetch('https://photon.komoot.io/api/?limit=5&lang=en&lat='+center.lat+'&lon='+center.lng+'&q='+encodeURIComponent(q),{signal:request.signal});if(!r.ok)throw Error('Search service unavailable');const response=await r.json();results=(response.features||[]).filter(p=>p.geometry?.type==='Point').slice(0,5)}if(sequence!==searchSequence)return;searchCache.set(q.toLowerCase(),results);renderSuggestions(results)}catch(e){if(e.name!=='AbortError'&&sequence===searchSequence)searchResults.textContent='Place search unavailable. You can enter latitude, longitude.'}}
 searchInput.oninput=()=>{clearTimeout(searchTimer);searchSequence++;if(searchRequest)searchRequest.abort();hideSuggestions();if(searchInput.value.trim().length<2)return;const sequence=searchSequence;searchTimer=setTimeout(()=>searchPlaces(sequence),Math.max(400,1000-(Date.now()-lastSearchStarted)))};
 searchForm.onsubmit=e=>{e.preventDefault();clearTimeout(searchTimer);searchSequence++;searchPlaces(searchSequence)};
 document.addEventListener('pointerdown',e=>{if(!searchForm.contains(e.target)){clearTimeout(searchTimer);searchSequence++;if(searchRequest)searchRequest.abort();hideSuggestions()}});
 searchInput.addEventListener('keydown',e=>{if(e.key==='ArrowDown'){const first=searchResults.querySelector('button');if(first){e.preventDefault();first.focus()}}if(e.key==='Escape'){searchSequence++;if(searchRequest)searchRequest.abort();hideSuggestions()}});
 document.addEventListener('keydown',e=>{if(e.key!=='Escape'||e.defaultPrevented)return;if($('dialog').open)return;e.preventDefault();if(drawMode){if(drawPoints.length){drawPoints.pop();drawChoice=null;drawInsert=false;refreshDrawing()}else stopDrawing();return}if(window.NVVMeasurement?.isActive()){window.NVVMeasurement.undo();return}cancelSelection();show(null);searchResults.hidden=true});
 function movable(el,head){if(!head)return;head.classList.add('drag-dialog-handle');let drag;head.addEventListener('pointerdown',e=>{if(e.button!==0||e.target.closest('button,input,select,a'))return;const b=el.getBoundingClientRect();drag={id:e.pointerId,x:e.clientX,y:e.clientY,left:b.left,top:b.top};head.setPointerCapture(e.pointerId);e.preventDefault()});head.addEventListener('pointermove',e=>{if(!drag||drag.id!==e.pointerId)return;const v=window.visualViewport,w=v?.width||innerWidth,h=v?.height||innerHeight;el.style.position='fixed';el.style.margin='0';el.style.right='auto';el.style.bottom='auto';el.style.left=Math.max(0,Math.min(w-el.offsetWidth,drag.left+e.clientX-drag.x))+'px';el.style.top=Math.max(v?.offsetTop||0,Math.min(h+(v?.offsetTop||0)-Math.min(el.offsetHeight,80),drag.top+e.clientY-drag.y))+'px';if(el===$('dialog'))saveMapPoint=null});const end=()=>{drag=null};head.addEventListener('pointerup',end);head.addEventListener('pointercancel',end)}
 for(const p of Object.values(panels))movable(p,p.querySelector('.panel-head'));movable(editor,editor.querySelector('.editor-head'));movable($('dialog'),$('dialog-title'));

 // Touch users can hold a symbol to see its name without activating it.
 let heldTool=null,holdTimer=null,suppressTool=null;document.addEventListener('pointerdown',e=>{const b=e.target.closest('.symbol-tool,.layers-launcher');if(!b)return;heldTool=b;holdTimer=setTimeout(()=>{suppressTool=b;toast(b.getAttribute('aria-label')||b.title)},600)});for(const name of ['pointerup','pointercancel','pointermove'])document.addEventListener(name,()=>{clearTimeout(holdTimer);heldTool=null});document.addEventListener('click',e=>{if(suppressTool&&suppressTool.contains(e.target)){e.preventDefault();e.stopImmediatePropagation()}suppressTool=null},true);
 requestAnimationFrame(()=>map.invalidateSize());
})();



